In [ ]:
from tensorflow.keras import  datasets
from keras.layers import Input, Dense, Flatten
from keras.models import Sequential
from matplotlib import pyplot as plt

(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

#Normalize image pixel values.
x_train = x_train/255
x_test = x_test/255
y_train

11490434/11490434 [==============================] - 0s 0us/step


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
import numpy as np
np.unique(y_train)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
y_train[0:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [ ]:
#flatten inside the model, batch =None
model=Sequential()
model.add(Input(shape=(28,28,1)))
# model.add(Input(batch_shape=(64,28,28,1)))
model.add(Flatten())
model.add(Dense(120,activation = 'tanh'))
model.add(Dense(84,activation = 'tanh'))
model.add(Dense(10,activation = 'softmax'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 784)               0         
                                                                 
 dense_15 (Dense)            (None, 120)               94200     
                                                                 
 dense_16 (Dense)            (None, 84)                10164     
                                                                 
 dense_17 (Dense)            (None, 10)                850       
                                                                 
Total params: 105214 (410.99 KB)
Trainable params: 105214 (410.99 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#flatten inside the model, batch =32
model=Sequential()
model.add(Flatten(input_shape=(28,28,1)))
# model.add(Flatten(batch_input_shape=(32,28,28,1)))
model.add(Dense(120,activation = 'tanh'))
model.add(Dense(84,activation = 'tanh'))
model.add(Dense(10,activation = 'softmax'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_5 (Flatten)         (None, 784)               0         
                                                                 
 dense_18 (Dense)            (None, 120)               94200     
                                                                 
 dense_19 (Dense)            (None, 84)                10164     
                                                                 
 dense_20 (Dense)            (None, 10)                850       
                                                                 
Total params: 105214 (410.99 KB)
Trainable params: 105214 (410.99 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#flatten outside the model using reshape
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

model=Sequential()
# model.add(Input(shape=(784,)))
# model.add(Dense(120,activation = 'tanh',input_shape=(784,)))
# model.add(Dense(120,activation = 'tanh',input_shape=(784,)))
model.add(Dense(120,activation = 'tanh',batch_input_shape=(32,784,)))
model.add(Dense(84,activation = 'tanh'))
model.add(Dense(10,activation = 'softmax'))
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_21 (Dense)            (32, 120)                 94200     
                                                                 
 dense_22 (Dense)            (32, 84)                  10164     
                                                                 
 dense_23 (Dense)            (32, 10)                  850       
                                                                 
Total params: 105214 (410.99 KB)
Trainable params: 105214 (410.99 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
